server:
  port: 8081

spring:
  application:
    name: nonmus
  datasource:
    url: jdbc:postgresql://localhost:5401/ledger
    username: user
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # ADD THIS SECTION TO FIX THE INSTANT SERIALIZATION:
      properties:
        spring.json.add.type.headers: true
        # This tells Jackson to add all registered classpath modules (like JSR310) to the Kafka mapper
        spring.jackson.modules: com.fasterxml.jackson.datatype.jsr310.JavaTimeModule

    consumer:
      group-id: ledger-group
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring:
          json:
            trusted:
              packages: "*"

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
