spring:
  application:
    name: payment-gateway
  datasource:
    url: jdbc:postgresql://localhost:5400/payment_gateway
    username: user
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  redis:
    host: localhost
    port: 6379
    password: "root"

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: payment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

swiftpay:
  ledger:
    base-url: ${LEDGER_BASE_URL:http://ledger:8080}
  kafka:
    topics:
      payment-initiated: ${PAYMENT_INITIATED_TOPIC:payment-initiated}
      payment-completed: ${PAYMENT_COMPLETED_TOPIC:payment-completed}
      payment-failed: ${PAYMENT_FAILED_TOPIC:payment-failed}
